"""
M5 -- merge the LoRA into the base weights and emit the deployable artefacts.

    python3 merge_export.py --adapter adapters/v1 --out dist/sentri-v1

Produces:
    dist/sentri-v1/                 merged fp16 HF checkpoint
    dist/sentri-v1/SHA256SUMS       checksums over every shipped file
    dist/sentri-v1/SENTRIClassifier.Modelfile
                                    generated from prompt.py, never hand-edited

The Modelfile is generated rather than written because it and run_eval.py have
already disagreed once. If the deployed system prompt is typed out by hand it
will drift from the one the model was trained under, and nothing will report
the drift -- the model just gets quietly worse.

GGUF conversion is left as a printed command rather than run here: it needs
llama.cpp, which is not a dependency of this repo, and the quantisation choice
belongs to whoever is deploying.

Merging runs on CPU in bf16 (~6GB RSS). Merging into NF4 weights would bake
the quantisation error into the base and is not done.
"""

import argparse
import hashlib
import json
from pathlib import Path

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

import prompt as P

MODELFILE = """# GENERATED by merge_export.py -- do not edit.
# System prompt is the single source of truth in osava-ft/prompt.py
# (variant={variant}, scale={scale}). Regenerate after any change there.
#
# Contract differences from the phi3:mini version this replaces:
#   severity is FIRST          scored by log-likelihood before any other field (R4)
#   no `confidence`            replaced by the routing margin computed host-side (R7)
#   no `recommendedPath`       routing is no longer the model's decision
#   severity is {n}-way          `critical` describes an incident, not an event (R5)
#
# adapter: {adapter}
# base:    {base}

FROM {gguf}

SYSTEM \"\"\"
{system}
\"\"\"

PARAMETER temperature 0.1
PARAMETER top_p 0.9
PARAMETER repeat_penalty 1.1
PARAMETER num_ctx {num_ctx}
PARAMETER stop "<|im_end|>"
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="HuggingFaceTB/SmolLM3-3B")
    ap.add_argument("--adapter", default="adapters/v1")
    ap.add_argument("--out", default="dist/sentri-v1")
    ap.add_argument("--variant", choices=list(P.TAIL), default="strict")
    ap.add_argument("--scale", choices=list(P.SCALES), default="4way")
    ap.add_argument("--gguf", default="./osava-smollm-q4_k_m.gguf")
    ap.add_argument("--num-ctx", type=int, default=32768,
                    help="Ollama context window. Must be >= the caller's "
                         "TOKEN_BUDGET (HIRA cascadeRouter.ts) -- every input "
                         "passes through the classifier, so its window bounds "
                         "the whole cascade. SmolLM3 has GQA (4 KV heads of "
                         "16), so the cache is 0.07 MB/token: 2.25GB at 32k "
                         "against phi3-mini's 12GB.")
    ap.add_argument("--modelfile-only", action="store_true")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    if not args.modelfile_only:
        print(f"loading {args.model} in bf16 on cpu ...")
        base = AutoModelForCausalLM.from_pretrained(
            args.model, dtype=torch.bfloat16, device_map="cpu")
        print(f"applying {args.adapter} ...")
        merged = PeftModel.from_pretrained(base, args.adapter).merge_and_unload()
        merged.save_pretrained(out, safe_serialization=True)
        AutoTokenizer.from_pretrained(args.model).save_pretrained(out)
        print(f"merged -> {out}")

    (out / "SENTRIClassifier.Modelfile").write_text(MODELFILE.format(
        variant=args.variant, scale=args.scale, n=len(P.SCALES[args.scale]),
        adapter=args.adapter, base=args.model, gguf=args.gguf,
        num_ctx=args.num_ctx,
        # KEEP the /system_override token. An earlier version stripped it on
        # the assumption that Ollama does its own templating -- it does not.
        # The GGUF embeds SmolLM3's chat template verbatim, and Ollama renders
        # SYSTEM through it, so without the token the deployed model receives
        # the `## Metadata` header (today's date, `Reasoning Mode: /think`)
        # that training and evaluation both suppressed. That is a silent
        # train/serve prompt mismatch on every single inference.
        system=P.system_prompt(args.variant, args.scale, override=True).strip()))

    sums = []
    for f in sorted(out.rglob("*")):
        if f.is_file() and f.name != "SHA256SUMS":
            h = hashlib.sha256(f.read_bytes()).hexdigest()
            sums.append(f"{h}  {f.relative_to(out)}")
    (out / "SHA256SUMS").write_text("\n".join(sums) + "\n")
    print(f"checksums -> {out/'SHA256SUMS'} ({len(sums)} files)")

    print(f"""
next:
  python3 llama.cpp/convert_hf_to_gguf.py {out} --outfile {out}/f16.gguf --outtype f16
  llama.cpp/build/bin/llama-quantize {out}/f16.gguf {out}/{Path(args.gguf).name} Q4_K_M
  ollama create osava-smollm --quantize q4_K_M -f {out}/SENTRIClassifier.Modelfile""")


if __name__ == "__main__":
    main()
